### ISSUE TITLE
如果并发量比较高，redis是否有压力？还有redis挂了的话，分流的使用受影响吗

### ISSUE THREAD

**Issue by gaolin713** [CNSRE/ABTestingGateway#105]
如果并发量比较高，redis是否有压力？还有redis挂了的话，分流的使用受影响吗

**Comment by zb1749** [comment]
redis即是数据库，没了就炸，建议redis HA

**Comment by BG2BKK** [comment]
@gaoyaqiu 1. 容量规划确实是需要提前研判的；2. redis的压力，取决于如何使用，比如访问周期、节点数量等，目前看分钟级、万节点一下的查询，redis还是能应对的，如果是10w节点及以上，需要想别的方案；3. redis，或者策略数据库挂掉，影不影响使用，还是取决于业务和设计

**Comment by gl2378** [comment]
了解，谢了。
