### ISSUE TITLE
运行示例的时候出错

### ISSUE THREAD

**Issue by MinjieTao** [CNSRE/ABTestingGateway#23]
你好，

我是nginx新手，
按照README里的示例，在跑到
_# 启动灰度系统，proxy server，灰度系统的配置也写在conf/nginx.conf中_
_9. /usr/local/nginx/sbin/nginx -p `pwd` -c conf/nginx.conf_

的时候出现下面错误
_"nginx: [emerg] unknown directive "uniqueid_prefix" in xxx"_

请问，unqiueid_prefix是哪个module里的命令。 给的示例又需要哪些module才能跑呢？

**Comment by BG2BKK** [comment]
你好，这个指令是我们用到的一个第三方模块，仅仅作为每个req的id，在这里用不着；抱歉影响使用；我已经修改并更新repo，请重试下

**Comment by MinjieTao** [comment]
我试了一下，会用到一个变量_$request\_uid_,我把用到这个变量的地方都注释了就可以跑了

**Comment by BG2BKK** [comment]
好的，这个变量仅仅用来给req打tag的
