### ISSUE TITLE
你好，请问在运行时设置的规则，可以具体到location级别吗？现在的都是到servername级别的？

### ISSUE THREAD

**Issue by fankeke** [CNSRE/ABTestingGateway#33]
你好，请问在运行时设置的规则，可以具体到location级别吗？现在的都是到servername级别的？

我看到好像是可以在hostname=servername.location这样设置的，但是好像达不到要求。。。

**Comment by BG2BKK** [comment]
你好，可以设置location级别的运行时信息，在location中有 set $hostkey
 abcde；的设置，设置运行时信息时以abcde为hostname就可以设置location级别的运行时信息

2016-06-12 11:17 GMT+08:00 fankeke <notifications@github.com>:

> 你好，请问在运行时设置的规则，可以具体到location级别吗？现在的都是到servername级别的？
>
> 我看到好像是可以在hostname=servername.location这样设置的，但是好像达不到要求。。。
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CNSRE/ABTestingGateway/issues/33>, or mute the thread
> <https://github.com/notifications/unsubscribe/AA0sgWEsYcF-FJ5eE7BJrFkgOg3O6-KLks5qK3pEgaJpZM4IzsWF>
> .
>



-- 
黄振栋
bg2bkk@gmail.com
Phone：15010359288
personal site: https://bg2bkk.github.io

**Comment by fankeke** [comment]
Ok了。谢谢：）
其实你在wiki里面说了的，在location 下面设置 set $hostkey servername.loc 即可。
