### ISSUE TITLE
iprange的offset作用是什么？

### ISSUE THREAD

**Issue by yfgu** [CNSRE/ABTestingGateway#41]
iprange.lua里面将ip转换为long型时的offset的作用是什么，怎么决定取值的？

**Comment by BG2BKK** [comment]
这个是这样的，在redis中使用zset来存储数据时，处于ip段两端的ip容易被混淆，看做存在在两个段里，如果有一个offset，在一个ip段的起始减去0.3，在ip段的结尾加上0.3，在zrangebyscore的时候可以清爽的获得比该ip所在的段。当两个ip段连着的时候，前一个段的最后一个ip，和后一个段的第一个ip，通过加减offset，做成两个值
