### ISSUE TITLE
iprange设置cache的key/value

### ISSUE THREAD

**Issue by yfgu** [CNSRE/ABTestingGateway#42]
读了代码，在iprange的分流方式的时候，在nginx的cache里面设置的key/value是用户访问的ip2long的值/upstream值，如果用户访问量很大的话，会不会有问题？
另外，cache的超时时间设置多少比较适合？

**Comment by BG2BKK** [comment]
你好，感谢你对项目的兴趣。这里ngx_lua的shdict在访问量大的时候，依然不会是瓶颈，至少读取进程内的内存数据，比经过IO读取数据库要快的多。我们压测时的并发数据是70K没有问题，而一般机器的qps能达到10k的不多，所以不会是问题。

cache超时时间我们认为60s比较合适，属于不长也不短的设置。

代码的develop分支，在风格、结构和编码方式上都比较新，请同时看看develop分支，多多批评:)

关于策略同步机制，我目前倾向于采用ngx timer定时任务在后台拉取分流策略，而不是现在每台机器都部署redis。

**Comment by yfgu** [comment]
ngx timer定时任务在后台拉取分流策略是做什么用的，和只部署一台redis有什么关系？
