### ISSUE TITLE
admin/policy.lua的set方法的policyMod为什么是全局的

### ISSUE THREAD

**Issue by yfgu** [CNSRE/ABTestingGateway#55]
admin/policy.lua的set方法的policyMod为什么是全局的？其他方法，比如check之类是local的policyMod。

**Comment by BG2BKK** [comment]
Lua中的policyMod:FunctionName不是类似于cpp的类内static那种用法，这个check或者set是lua table的类内成员，局部的。

**Comment by yfgu** [comment]
你是说policyMod是admin/policy.lua这个table的类内成员？那为什么check的function里面是local的，但是set的function里面不是申明local的？

**Comment by BG2BKK** [comment]
啊，我没有说policyMod是policy.lua的类内成员，我说的是  对于 policyMod:FunctionName来说，FunctionName是policyMod的类内成员。

你的问题是，check函数里的pfunc中，policyMod这个变量是local的，而set的pfunc中这个变量却没有用local。是这样的，在local functioin中的变量，不论有没有local修饰，都是局部的。这里我确实写的不严谨，没有统一。

**Comment by yfgu** [comment]
明白了，是为了在func里面共享变量。谢谢！
