### ISSUE TITLE
loadfile 在linux上 使用相对路径读取不到lua文件

### ISSUE THREAD

**Issue by yfgu** [CNSRE/ABTestingGateway#62]
在读取lib/abtesting/diversion/*和lib/abtesting/usrinfo/*文件的时候, 使用loadfile替换require, loadfile的文件名使用相对路径, 结果总是报没有这个文件夹或者文件的错误,请问这个是怎么回事?

**Comment by yfgu** [comment]
准确的说是有时候加载得到,有时候会加载不到

**Comment by BG2BKK** [comment]
nginx的路径都是确定的，如果说时好时坏，可以考虑下，加载不到的时候是因为lua文件有错误，导致load失败

**Comment by yfgu** [comment]
谢谢。找到原因了，虽然说linux上可以使用相对路径，但是相对路径是相对于执行的命令行所在目录。现在在nginx里面配置项目路径，文件里面拼接路径。
