### ISSUE TITLE
请问abtestinggateway可以与dyups模块配合使用吗？

### ISSUE THREAD

**Issue by turbinefish** [CNSRE/ABTestingGateway#81]
我用的是tengine，增加了ngx_http_dyups_module模块，想通过abtestinggateway做动态分流，通过dyups做upstream的动态修改，但发现同时启动这两个后，dyups修改的upstream内容没有被abtestinggateway识别到，仍是跳转到原upstream内容的server上。

**Comment by BG2BKK** [comment]
ab根据策略查找到upstream，与upstream内部的server list不相关；server list对ab是透明的，如果变更的是upstream内部的server list，ab将请求转发到upstream后，nginx的upstream模块决定请求分发到哪个server；如果变更的是upstream名称，需要重新设置策略
