### ISSUE TITLE
急急急 ！为什么没走分流策略呢

### ISSUE THREAD

**Issue by fonerfang** [CNSRE/ABTestingGateway#83]
生效分流策略，符合beta1，但是就是到stable。下面是error.log日志，有遇到过类似情况额吗？
redis里是有策略数据的
 success proxypass to upstream http://stable, extrainfo : the req has no target upstream

**Comment by fonerfang** [comment]
code : 40201, desc : lua runtime error ../lib/abtesting/utils/log.lua:33: bad argument #5 to 'log' (expected table to have __tostring metamethod), errstack : stack traceback:
        ../lib/abtesting/error/handler.lua:17: in function <../lib/abtesting/error/handler.lua:7>
        [C]: in function 'log'
        ../lib/abtesting/utils/log.lua:33: in function 'debug'
        /usr/local/dygateway/diversion/diversion.lua:219: in function </usr/local/dygateway/diversion/diversion.lua:202>
        [C]: in function 'xpcall'
        /usr/local/dygateway/diversion/diversion.lua:332: in function </usr/local/dygateway/diversion/diversion.lua:1>,

**Comment by yfgu** [comment]
一步步log吧，都是这个过来的

**Comment by fonerfang** [comment]
你这不废话嘛，有遇到类似问题，或者知道大概哪块出问题，可以给指点一下，指点不了在这儿废什么话！不愿分享经验就不分享，来这里装什么。另外，看清楚，年前的问题，早解决了。同事按部署文档操作忘记配置LUAJIT_LIB、LUAJIT_INC环境变量导致，日志啥都看不出来，OK？！
