### ISSUE TITLE
如果做前端页面的AB测试

### ISSUE THREAD

**Issue by yfgu** [CNSRE/ABTestingGateway#84]
这个在前端的AB测试中怎么用？
例如：
    两套页面，一套切30%流量、另外一套切70%流量。
    某用户这次登录看到的都是A页面，但是下次登录都是B页面或者A页面。

**Comment by yfgu** [comment]
现在想到的是用percent，用seed因子固定随机数。但是这样的话，如何保证这个随机因子在页面关闭前都是固定的同一个值，这个值怎么传递。

**Comment by jie123108** [comment]
前端记录cookie. 并且只在不存在该key时, 才生成,并写入.
page: a
page: b
生成时,按你需要的概率来生成就可以了.




原始邮件
发件人:yfgunotifications@github.com
收件人:CNSRE/ABTestingGatewayABTestingGateway@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年3月9日(周五) 15:43
主题:Re: [CNSRE/ABTestingGateway] 如果做前端页面的AB测试 (#84)


现在想到的是用percent，用seed因子固定随机数。但是这样的话，如何保证这个随机因子在页面关闭前都是固定的同一个值，这个值怎么传递。

**Comment by yfgu** [comment]
好的，非常感谢！
