### ISSUE TITLE
centos7下安装ABTestingGateway步骤分享

### ISSUE THREAD

**Issue by 20100507** [CNSRE/ABTestingGateway#91]
下面是相关安装包 百度云盘我会给出下面的安装包分享地址！百度云链接：
链接：https://pan.baidu.com/s/1ARUubEJVSoZbFFnQMxzwMA 密码：l7p0
注意lua-nginx-module版本，lua-resty-core版本，版本兼容是最大的坑！
```
-rw-r--r--.  1 root root  221213 2月  14 2012 lua-5.1.5.tar.gz
drwxrwxr-x.  4  500   500   4096 7月  20 17:24 lua-cjson-2.1.0
drwxr-xr-x.  6 www  redis    100 5月  15 2015 LuaJIT-2.0.4
drwxr-xr-x. 11 root root     237 7月  20 17:01 lua-nginx-module
drwxr-xr-x.  6 root root     211 7月  20 19:03 lua-resty-core
drwxr-xr-x.  9 1001 www      186 7月  20 17:26 nginx-1.10.3
drwxrwxr-x.  9 root root     203 9月  26 2013 ngx_devel_kit
drwxr-xr-x.  7 1169  1169   8192 1月  11 2017 pcre-8.40
```
1.安装lua,这里使用lua-5.1.5版本，**5.2不支持**
      **github官方给出的openresty对lua5.2不支持**[_Install LuaJIT 2.0 or 2.1 (recommended) or Lua 5.1 (Lua 5.2 is not supported yet). LuaJIT can be downloaded from the LuaJIT project website and Lua 5.1, from the Lua project website. Some distribution package managers also distribute LuaJIT and/or Lua_.]_
```
`[root@nginx1 nginx]# cd lua-5.1.5/`
[root@nginx1 lua-5.1.5]# make linux
[root@nginx1 lua-5.1.5]# make install
```
2.修改nginx/lua-cjson-2.1.0/Makefile这个文件，2个路径需要修改为
  ```
LUA_INCLUDE_DIR = /usr/local/luajit/include/luajit-2.0
  LUA_BIN_DIR = /usr/bin
```
3.设置环境变量
   ```
LUAJIT_LIB=/usr/local/luajit/lib
   LUAJIT_INC=/usr/local/luajit/include/luajit-2.0
```
  `[root@nginx1 lua-5.1.5]# vim /etc/profile`
4.安装nginx相关依赖
  ` yum install -y make gcc gcc-c++ pcre-devel openssl-devel zlib-devel GeoIP-devel`
5.编译安装LuaJIT
 ` ` cd /nginx/LuaJIT-2.0.4 && make && make install PREFIX=/usr/local/luajit``
6.执行nginx安装
```
  cd /nginx/nginx-1.10.3 && ./configure --prefix=/usr/local/nginx --with-http_v2_module --with- 
    http_geoip_module --with-http_ssl_module --with-http_stub_status_module --with-threads --with- 
    http_gzip_static_module --with-http_realip_module --with-ld-opt=-ldl --with-ld-opt=-Wl,- 
   rpath,/usr/local/luajit/lib --add-module=../ngx_devel_kit/ --add-module=../lua-nginx-module/ && 
   make && make install
```
7.添加支持json解析
` `  `cd /nginx/lua-cjson-2.1.0 && make && make install && cp cjson.so /usr/lib64/lua/5.1/```
8.替换相关目录 否则运行测试demo报错
    clone  ABTestingGateway,注意下载https://github.com/openresty/lua-resty-core/tree/v0.1.6 这个版本 
    lib 目录下的ngx和resty目录 copy 到ABTestingGateway的lib/lua-resty-core目录下替换，强调一下注意 
    版本
9.运行nginx+abtestingGateway
   切换到ABTestingGateway的utils目录启动运行abtesting.sh,正常可以测试通过运行demo示例
  ` [root@nginx1 utils]# ./abtesting.sh`

**Comment by 20100507** [comment]
问题已经解决了lua版本需要5.2.0以及以上！这个是我相关的编译模块以上所使用到的模块加上这个版本的nginx可以运行成功！
`./configure --prefix=/usr/local/nginx --user=root --group=root --with-http_stub_status_module --with-http_v2_module --with-http_ssl_module --with-ipv6 --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-openssl=../openssl-1.0.2h --with-pcre=../pcre-8.38 --with-pcre-jit --with-ld-opt='-ljemalloc' --with-ld-opt="-Wl,-rpath,/usr/local/luajit/lib" --add-module=/usr/local/src/ngx_devel_kit-0.2.19 --add-module=/usr/local/src/lua-nginx-module-0.10.10
`
```
[root@nginx1 logs]# curl 127.0.0.1:8080/ab_admin?action=policygroup_set -d '{"1":{"divtype":"uidsuffix","divdata":[{"suffix":"1","upstream":"beta1"},{"suffix":"3","upstream":"beta2"},{"suffix":"5","upstream":"beta1"},{"suffix":"0","upstream":"beta3"}]},"2":{"divtype":"arg_city","divdata":[{"city":"BJ","upstream":"beta1"},{"city":"SH","upstream":"beta2"},{"city":"XA","upstream":"beta1"},{"city":"HZ","upstream":"beta3"}]},"3":{"divtype":"iprange","divdata":[{"range":{"start":1111,"end":2222},"upstream":"beta1"},{"range":{"start":3333,"end":4444},"upstream":"beta2"},{"range":{"start":7777,"end":2130706433},"upstream":"beta2"}]}}'
{"desc":"success ","code":200,"data":{"groupid":0,"group":[0,1,2]}}
```

**Comment by 20100507** [comment]
对于安装lua和相关的依赖可以参考这篇文章
https://blog.csdn.net/qq_25551295/article/details/51744815

**Comment by chentian610** [comment]
安装第一步的时候出错了啊@20100507
